---
title: "testing table"
author: "Ericka B. Smith"
date: "2/15/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(kableExtra)
library(here)
library(tidyverse)
```


```{r}
(dat <- readRDS(here("results", "table_3_equivalent.rds")))
```



```{r}
tst <- dat %>% 
  ungroup() %>%
  mutate(lcz = fct_drop(lcz, only = "0")) %>%
  pivot_wider(names_from=tt, values_from=c(total_n_pixels, n_polygons)) %>%
  unite("Train", c(n_polygons_train, total_n_pixels_train), sep = "        (") %>%
  unite("Test", c(n_polygons_test, total_n_pixels_test), sep = " (") %>%
  mutate(Train = paste(Train, ")", sep=""),
         Test = paste(Test, ")", sep=""))
# 
# 
#   relocate(lcz, n_polygons_train, total_n_pixels_train, n_polygons_test, total_n_pixels_test) %>%
#   rename

```

```{r}


```



```{r}
#kable(tst, format="latex", booktabs=T, caption = "etc etc") %>% add_header_above(., c(' '=1, 'Parts'=4'))
 kable(tst, format='latex',align='c',linesep='',booktabs=TRUE,escape=FALSE,
        col.names = linebreak(colnames(tst),align = 'c')) %>%
  add_header_above(c(" " = 1, "title" = 2)) %>%
  #collapse_rows(columns = c(1,3),valign = 'middle')%>%
  kable_styling(latex_options = c('striped','HOLD_position','scale_down'))
```


