---
title: "Initial Data Cleaning"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(raster)
library(rgdal)
library(here)
library(magrittr)
```

Strategy is to load all scenes in as rasterstacks and the lcz and polygon information as a dataframe.

The scenes are then stacked and converted to a dataframe.

LCZ and scene data is bound by column and saved in `results` as `hk_df.rds` file

```{r load-data}
lcz <- readRDS(here("results", "lcz_and_poly_ids.RDS"))

# make file lists
scene_1 <- list.files(here("data/hong_kong/landsat_8", "LC81220442013333LGN00"),
                       pattern='.tif', all.files=TRUE, full.names=TRUE)

scene_2 <- list.files(here("data/hong_kong/landsat_8", "LC81220442014288LGN00"),
                       pattern='.tif', all.files=TRUE, full.names=TRUE)

scene_3 <- list.files(here("data/hong_kong/landsat_8", "LC81220442014320LGN00"),
                       pattern='.tif', all.files=TRUE, full.names=TRUE)

scene_4 <- list.files(here("data/hong_kong/landsat_8", "LC81220442015291LGN00"),
                       pattern='.tif', all.files=TRUE, full.names=TRUE)

# actually import each scene
s1 <- stack(scene_1)
s2 <- stack(scene_2)
s3 <- stack(scene_3)
s4 <- stack(scene_4)
```



```{r change-colnames}
names(s1) <- c("b1", "b2", "b3", "b4", "b5", "b6", "b7", "b10", "b11")
names(s2) <- c("b1", "b2", "b3", "b4", "b5", "b6", "b7", "b10", "b11")
names(s3) <- c("b1", "b2", "b3", "b4", "b5", "b6", "b7", "b10", "b11")
names(s4) <- c("b1", "b2", "b3", "b4", "b5", "b6", "b7", "b10", "b11")
```


```{r stack-all}
scenes <- stack(s1, s2, s3, s4)
scenes_df <- as.data.frame(scenes)
```

```{r put-it-all-together}
lcz_and_scenes_df <- bind_cols(lcz, scenes_df)
```

```{r fix-data-types}
names(lcz_and_scenes_df)[1] <- "lcz"
lcz_and_scenes_df$lcz %<>% factor()
# left polygon_id as char because undecided if I'd rather go numeric or factor
```


```{r save}
saveRDS(lcz_and_scenes_df, here("results", "hk_df.rds"))
```


